### ISSUE TITLE
v0.8.2 breaks semver

### ISSUE THREAD

**Issue by bbannier** [romankoblov/prettydiff#28]
prettydiff-0.8.2 [introduced](https://github.com/oli-obk/prettydiff/commit/82d4f65c7302f72e3adc639a985923b213acf86f) new required fields to `text::ContextConfig` which breaks semver, i.e., the following builds with 0.8.1, but not with 0.8.2 anymore:

```rust
use prettydiff::text::{ContextConfig, LineChangeset};

fn main() {
    let diff = LineChangeset::new(vec![], vec![]);
    diff.format_with_context(
        Some(ContextConfig {
            context_size: 2,
            skipping_marker: "",
        }),
        true,
    );
}
```

```
error[E0063]: missing fields `insert_color` and `remove_color` in initializer of `ContextConfig<'_>`
 --> src/main.rs:6:14
  |
6 |         Some(ContextConfig {
  |              ^^^^^^^^^^^^^ missing `insert_color` and `remove_color`
```

A package with a dependency `prettydiff = "0.8.0"` would now suddenly refuse to build.

prettydiff is still on `0.*` so one could argue that this is okay, but it would still be nice to avoid this by being a little more liberal by using minor releases. One approach to fix this situation would be to yank prettydiff-0.8.3 and rereleased it as prettydiff-0.9.0.

**Comment by oli-obk** [comment]
Yanked, thx. I'll make semver checks work before I publish again. Next breaking change should also make that no exhaustive I guess

**Comment by mkatychev** [comment]
@oli-obk https://github.com/obi1kenobi/cargo-semver-checks is really hand for this

**Comment by oli-obk** [comment]
I'm aware, and even have set it up as a github action, I just haven't finished setting up the keys for the GH action to work 🙈

**Comment by oli-obk** [comment]
Setup semver checks and published 0.9.0
